version: 2.1

orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build:
    docker:
      - image: cimg/node:16.8.0
    working_directory: ~/joel
    steps:
      - checkout
      - run: npm install
      # - run: npm test
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: install-npm-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm run test:unit
      - run: # run code coverage report
          name: code-coverage
          command: npm run coverage
      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          prefix: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - run: # test what branch we're on.
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - run: # run build
          name: Build
          command: npm run build
      # - coveralls/upload
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main

# circleci config validate